server:
  port: 9008
spring:
  application:
    name: tensquare_user
  datasource:
    url: jdbc:mysql://192.168.0.100:3306/tensquare_user?characterEncode=UTF8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  rabbitmq:
    addresses: 192.168.0.100
    port: 5672
  redis:
    host: 192.168.0.100